export default interface Player {
  player_id: string;
  player_name: string;
  valid_from: Date;
  valid_until: Date | null;
  deceased: boolean;
  anticapitalism: number;
  base_thirst: number;
  buoyancy: number;
  chasiness: number;
  coldness: number;
  continuation: number;
  divinity: number;
  ground_friction: number;
  indulgence: number;
  laserlikeness: number;
  martyrdom: number;
  moxie: number;
  musclitude: number;
  omniscience: number;
  overpowerment: number;
  patheticism: number;
  ruthlessness: number;
  shakespearianism: number;
  suppression: number;
  tenaciousness: number;
  thwackability: number;
  tragicness: number;
  unthwackability: number;
  watchfulness: number;
  pressurization: number;
  cinnamon: number;
  total_fingers: number;
  soul: number;
  fate: number;
  peanut_allergy: boolean;
  armor: string;
  bat: string;
  ritual: string;
  coffee: string;
  blood: string;
  url_slug: string;
  current_state: string;
  current_location: string;
  debut_gameday: number;
  debut_season: number;
  debut_tournament: number;
  incineration_season: number | null;
  incineration_gameday: number | null;
  incineration_phase: string | null;
  gameday_from: number | null;
  season_from: number | null;
  tournament_from: number | null;
  phase_type_from: string;
  position_id: number;
  position_type: string;
  team: string;
  team_abbreviation: string | null;
  team_id: string;
  modifications: string[];
  baserunning_rating: number;
  baserunning_stars: number;
  batting_rating: number;
  batting_stars: number;
  defense_rating: number;
  defense_stars: number;
  pitching_rating: number;
  pitching_stars: number;
}
